pub fn vesper() -> Vec<(&'static str, &'static str)> {
    vec![
        ("identifier", "#A5FCB6"),
        ("field_identifier", "#A5FCB6"),
        ("property_identifier", "#A5FCB6"),
        ("property", "#A5FCB6"),
        ("string", "#b1fce5"),
        ("keyword", "#a0a0a0"),
        ("constant", "#f6c99f"),
        ("number", "#f6c99f"),
        ("integer", "#f6c99f"),
        ("float", "#f6c99f"),
        ("variable", "#ffffff"),
        ("variable.builtin", "#ffffff"),
        ("function", "#f6c99f"),
        ("function.call", "#f6c99f"),
        ("method", "#f6c99f"),
        ("function.macro", "#f6c99f"),
        ("comment", "#585858"),
        ("namespace", "#f6c99f"),
        ("type", "#f6c99f"),
        ("type.builtin", "#f6c99f"),
        ("tag.attribute", "#c6a5fc"),
        ("tag", "#c6a5fc"),
        ("error", "#A5FCB6"),
    ]
}
