//! Shared internationalization backend for the Vix workspace.
//!
//! `rust_i18n`'s `t!` macro expands to `crate::_rust_i18n_t!`, and the `i18n!`
//! macro embeds the whole translation table into whichever crate invokes it.
//! In a multi-crate workspace that would embed the `locales/` directory once
//! per crate.
//! To avoid that, this crate invokes `i18n!` exactly once and re-exposes a
//! drop-in [`t!`] plus a [`surface!`] helper; consumer crates call
//! `vix_i18n::surface!()` at their root and use `vix_i18n::t!` (or bring it in
//! unqualified with `#[macro_use] extern crate vix_i18n;`). The full API is
//! documented because the workspace forbids missing docs.
//!
//! ## Lazy per-locale loading (T517)
//!
//! `rust_i18n::i18n!`'s own codegen unconditionally builds **every** locale's
//! flat `key -> value` map the first time any `t!()` call runs, even though a
//! process only ever queries one locale (plus English for the fallback walk)
//! — with 9 `locales/*.yml` files merged across every bundled locale, that's
//! tens of thousands of `HashMap::insert` calls done up front for translations
//! that are never read. There is no macro option to make that lazy: `i18n!`'s
//! `backend = ` argument only *extends* the eagerly-built table with another
//! backend, it doesn't replace the codegen that builds it.
//!
//! So this crate doesn't call `i18n!` at all. `build.rs` instead reuses
//! `rust_i18n_support::load_locales` — the exact function the macro itself
//! calls — to merge `locales/*.yml` at build time, then splits the result by
//! **locale** into one JSON blob per locale under `$OUT_DIR` (see
//! `LOCALE_BLOBS`, generated into this file via `include!`). `LazyBackend`
//! holds one [`OnceLock`] per locale and only deserializes a locale's blob the
//! first time something actually asks for a translation in it — so a typical
//! run parses at most two locales (the active one, and English for the
//! fallback walk) instead of all of them. Everything downstream of the
//! backend (`_rust_i18n_translate`/`_rust_i18n_try_translate`/the fallback
//! walk) is a hand-written copy of what `i18n!`'s own codegen produces, kept
//! behaviorally identical — only the backend underneath changed.
#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![warn(clippy::pedantic)]

use std::borrow::Cow;
use std::collections::HashMap;
use std::sync::{LazyLock, OnceLock};

use rust_i18n::Backend as _;

// Re-export rust_i18n so `$crate::rust_i18n::_tr!` resolves inside the `t!`
// expansion below without the consumer needing rust_i18n in scope by that path.
#[doc(hidden)]
pub extern crate rust_i18n;

#[doc(no_inline)]
pub use rust_i18n::{available_locales, locale, set_locale};

// `(locale code, raw JSON blob of that locale's key -> value map)` pairs,
// one per locale present in `locales/*.yml`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/locale_blobs.rs"));

/// A [`rust_i18n::Backend`] that parses each locale's translation table only
/// once something actually asks for a key in it, instead of eagerly building
/// every bundled locale's map at startup (T517).
struct LazyBackend {
    /// One slot per `LOCALE_BLOBS` entry, in the same order, populated on
    /// first use.
    parsed: Box<[OnceLock<HashMap<String, String>>]>,
}

impl LazyBackend {
    fn new() -> Self {
        Self {
            parsed: LOCALE_BLOBS.iter().map(|_| OnceLock::new()).collect(),
        }
    }

    fn locale_index(locale: &str) -> Option<usize> {
        LOCALE_BLOBS.iter().position(|&(code, _)| code == locale)
    }

    /// The parsed `key -> value` map for the locale at `index`, deserializing
    /// its embedded JSON blob the first time this is called.
    fn messages(&self, index: usize) -> &HashMap<String, String> {
        self.parsed[index].get_or_init(|| {
            let (code, blob) = LOCALE_BLOBS[index];
            serde_json::from_str(blob)
                .unwrap_or_else(|e| panic!("embedded locale blob for {code:?} is valid JSON: {e}"))
        })
    }
}

impl rust_i18n::Backend for LazyBackend {
    fn available_locales(&self) -> Vec<Cow<'_, str>> {
        LOCALE_BLOBS
            .iter()
            .map(|&(code, _)| Cow::Borrowed(code))
            .collect()
    }

    fn translate(&self, locale: &str, key: &str) -> Option<Cow<'_, str>> {
        let index = Self::locale_index(locale)?;
        self.messages(index)
            .get(key)
            .map(|v| Cow::Borrowed(v.as_str()))
    }

    fn messages_for_locale(&self, locale: &str) -> Option<Vec<(Cow<'_, str>, Cow<'_, str>)>> {
        let index = Self::locale_index(locale)?;
        Some(
            self.messages(index)
                .iter()
                .map(|(k, v)| (Cow::Borrowed(k.as_str()), Cow::Borrowed(v.as_str())))
                .collect(),
        )
    }
}

/// The one and only backend instance. Building it is cheap (one [`OnceLock`]
/// per locale, none of them populated yet) — the real work happens lazily in
/// `LazyBackend::messages`, per locale, on first use.
static _RUST_I18N_BACKEND: LazyLock<LazyBackend> = LazyLock::new(LazyBackend::new);

/// The fallback locale chain a lookup walks when the requested locale (and
/// any of its `rust_i18n`-style tag-truncation fallbacks — irrelevant here,
/// since vix's locale codes never carry subtags) has no value for a key.
/// Mirrors the `fallback = "en"` argument the crate's `i18n!` call used to
/// pass.
static _RUST_I18N_FALLBACK_LOCALE: &[&str] = &["en"];

#[inline]
fn _rust_i18n_backend_translate<'r>(locale: &str, key: &str) -> Option<Cow<'r, str>> {
    _RUST_I18N_BACKEND.translate(locale, key)
}

/// The RFC 4647-style tag-truncation fallback used to look up e.g.
/// `"zh-Hant-CN"` as `"zh-Hant"` then `"zh"` when the full tag has no value.
/// A no-op for every locale code vix bundles (none carry a `-` subtag) —
/// kept for behavioral parity with what `rust_i18n::i18n!`'s own codegen
/// generates under this exact name.
#[must_use]
pub fn _rust_i18n_lookup_fallback(locale: &str) -> Option<&str> {
    locale
        .rfind('-')
        .map(|n| locale[..n].trim_end_matches("-x"))
}

/// Translate `key` against `locale`, falling back to a readable placeholder
/// (`"<locale>.<key>"`, or bare `key` with no locale) when no translation —
/// active locale, tag-truncation fallback, or `_RUST_I18N_FALLBACK_LOCALE`
/// — resolves it. Called by the `t!` macro's expansion; not meant to be
/// called directly.
// The leading-underscore names in this file exist only to match, exactly,
// what `rust_i18n::i18n!`'s own codegen would have generated -- `surface!`'s
// `pub use` and the `t!` macro's `crate::_rust_i18n_try_translate` reference
// depend on these precise names, not sloppy "forgot to finish this" code.
#[allow(clippy::used_underscore_items)]
#[must_use]
pub fn _rust_i18n_translate<'r>(locale: &str, key: &'r str) -> Cow<'r, str> {
    _rust_i18n_try_translate(locale, key).unwrap_or_else(|| {
        if locale.is_empty() {
            key.into()
        } else {
            format!("{locale}.{key}").into()
        }
    })
}

/// Try to translate `key` against `locale`, walking the tag-truncation
/// fallback and then `_RUST_I18N_FALLBACK_LOCALE` before giving up.
/// `None` when nothing in that chain has a value for `key`. Called by the
/// `t!` macro's expansion; not meant to be called directly.
#[allow(clippy::used_underscore_items)]
pub fn _rust_i18n_try_translate<'r>(locale: &str, key: impl AsRef<str>) -> Option<Cow<'r, str>> {
    _rust_i18n_backend_translate(locale, key.as_ref()).or_else(|| {
        let mut current_locale = locale;
        while let Some(fallback_locale) = _rust_i18n_lookup_fallback(current_locale) {
            if let Some(value) = _rust_i18n_backend_translate(fallback_locale, key.as_ref()) {
                return Some(value);
            }
            current_locale = fallback_locale;
        }
        _RUST_I18N_FALLBACK_LOCALE
            .iter()
            .find_map(|locale| _rust_i18n_backend_translate(locale, key.as_ref()))
    })
}

/// Every bundled locale code, sorted. Cheap: locale codes are known without
/// parsing any locale's translation blob.
#[must_use]
pub fn _rust_i18n_available_locales() -> Vec<Cow<'static, str>> {
    let mut locales = _RUST_I18N_BACKEND.available_locales();
    locales.sort();
    locales
}

/// Translate a key against the shared locale table.
///
/// A drop-in replacement for [`rust_i18n::t!`] that resolves against this
/// crate's single embedded table instead of a per-crate one. Supports the same
/// forms: `t!("key")`, `t!("key", name = value)`, `t!("key", count = n)`, and
/// `t!("key", locale = "es")`.
#[macro_export]
macro_rules! t {
    ($($all:tt)*) => {
        $crate::rust_i18n::_tr!(
            $($all)*,
            _minify_key = false,
            _minify_key_len = 0,
            _minify_key_prefix = "t_",
            _minify_key_thresh = 0
        )
    };
}

/// Surface the translation lookup functions at the calling crate's root.
///
/// The `t!` expansion references `crate::_rust_i18n_try_translate`, which must
/// resolve in the crate where the translation happens. Invoke this once at the
/// root of every crate that uses [`t!`].
#[macro_export]
macro_rules! surface {
    () => {
        #[doc(hidden)]
        pub use $crate::{_rust_i18n_translate, _rust_i18n_try_translate};
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn translates_a_key_with_an_interpolated_argument_per_locale() {
        // Explicit `locale = ` args, never `set_locale` -- the active locale
        // is process-global and would race other tests running in parallel.
        assert_eq!(
            t!("status.locale", locale = "en", language = "English"),
            "Language: English"
        );
        assert_eq!(
            t!("status.locale", locale = "es", language = "Inglés"),
            "Idioma: Inglés"
        );
    }

    #[test]
    fn an_unknown_locale_falls_back_to_english() {
        assert_eq!(
            t!("status.locale", locale = "xx", language = "X"),
            "Language: X"
        );
    }

    #[test]
    fn an_unknown_key_falls_back_to_its_own_literal() {
        // A variable, not a `t!("literal")` call: `tests/i18n_keys.rs` scans
        // the workspace for exactly that shape and requires every such key
        // to exist in `locales/` -- this test deliberately uses one that
        // doesn't, to exercise the no-translation-found fallback.
        let key = "this.key.does.not.exist";
        assert_eq!(t!(key), "this.key.does.not.exist");
    }

    #[test]
    #[allow(clippy::used_underscore_items)]
    fn missing_translate_falls_back_to_locale_dot_key() {
        // `_rust_i18n_translate`'s own fallback (used by callers other than
        // the `t!` macro, which calls `_rust_i18n_try_translate` directly
        // and falls back to its own literal message instead) is a distinct
        // format: `"<locale>.<key>"`, or bare `key` for an empty locale.
        assert_eq!(
            _rust_i18n_translate("en", "this.key.does.not.exist"),
            "en.this.key.does.not.exist"
        );
        assert_eq!(
            _rust_i18n_translate("", "this.key.does.not.exist"),
            "this.key.does.not.exist"
        );
    }

    #[test]
    #[allow(clippy::used_underscore_items)]
    fn available_locales_lists_every_bundled_locale_sorted() {
        let locales = _rust_i18n_available_locales();
        assert!(
            locales.windows(2).all(|w| w[0] <= w[1]),
            "not sorted: {locales:?}"
        );
        for code in ["en", "es", "fr"] {
            assert!(
                locales.iter().any(|l| l == code),
                "missing {code:?}: {locales:?}"
            );
        }
    }

    #[test]
    fn only_the_locales_actually_queried_get_parsed() {
        // A fresh backend, not the shared static -- so other tests' lookups
        // (which may run first) don't leave every locale already parsed.
        let backend = LazyBackend::new();
        let en = LazyBackend::locale_index("en").expect("en is bundled");
        let es = LazyBackend::locale_index("es").expect("es is bundled");
        assert!(backend.parsed[en].get().is_none());
        assert!(backend.parsed[es].get().is_none());

        assert!(backend.translate("en", "status.locale").is_some());

        assert!(
            backend.parsed[en].get().is_some(),
            "en should now be parsed"
        );
        assert!(
            backend.parsed[es].get().is_none(),
            "es was never queried, so it should still be unparsed"
        );
    }
}
