//! Print every command available in the command palette's `>` mode: the i18n
//! label key (translated at runtime via `t!`) and the action id it dispatches
//! — the original, unchanged default behavior.
//!
//! `--write` instead (re)generates the three generated-reference pages T305
//! (`tasks.md`) calls for, straight from their real data sources so they can
//! never drift: `docs/reference/actions.md` (every action id
//! `App::run_action` can dispatch, with its resolved title and where that
//! title comes from), `docs/reference/settings.md` (every `Settings` field:
//! key, type, default, doc comment), and one
//! `docs/reference/keybindings-<keymap>.md` per keymap plus a
//! `keybindings-shared.md` for the bindings every keymap shares.
//!
//! Run with: `cargo run --example list_commands`            (print, as before)
//!       or: `cargo run --example list_commands -- --write` (regenerate docs/reference/)
//!
//! CI (T305): regenerate with `--write`, then `git diff --exit-code` — a
//! non-empty diff means a generated page drifted from its source.

#![warn(clippy::pedantic)]

#[macro_use]
extern crate vix_i18n;
vix_i18n::surface!();

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use vix::action_catalog::{self, dispatch_scan};
use vix::keybindings;
use vix::keymap_model::KEYMAPS;
use vix::menu::{self, Item};
use vix::palette::COMMANDS;
use vix::settings::Settings;

fn main() {
    // Fixed locale so `--write`'s output is byte-identical run to run,
    // regardless of the environment's own locale settings — the CI check
    // (`git diff --exit-code` against a regenerated copy) depends on it.
    vix_i18n::set_locale("en");

    if std::env::args().any(|a| a == "--write") {
        write_reference_docs(&workspace_root());
    } else {
        print_commands();
    }
}

/// This example's own package is the workspace root package.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn print_commands() {
    let width = COMMANDS.iter().map(|(key, _)| key.len()).max().unwrap_or(0);
    println!("Vix command palette — `>` commands\n");
    println!("  {:<width$}  action id", "label key (i18n)");
    println!("  {:<width$}  ---------", "-".repeat(width.min(16)));
    for (label_key, action) in COMMANDS {
        println!("  {label_key:<width$}  {action}");
    }
    println!("\n{} commands", COMMANDS.len());
}

fn write_reference_docs(root: &Path) {
    let out_dir = root.join("docs/reference");
    fs::create_dir_all(&out_dir).unwrap_or_else(|e| panic!("creating {}: {e}", out_dir.display()));

    write(&out_dir.join("actions.md"), &render_actions(root));
    write(&out_dir.join("settings.md"), &render_settings(root));
    write(
        &out_dir.join("keybindings-shared.md"),
        &render_shared_keybindings(),
    );
    for keymap in KEYMAPS {
        write(
            &out_dir.join(format!("keybindings-{}.md", keymap.id)),
            &render_keymap_keybindings(keymap),
        );
    }
    println!(
        "Wrote docs/reference/{{actions,settings,keybindings-shared}}.md and {} keybindings-<keymap>.md files",
        KEYMAPS.len()
    );
}

fn write(path: &Path, content: &str) {
    fs::write(path, content).unwrap_or_else(|e| panic!("writing {}: {e}", path.display()));
}

/// The title `App::action_title` (`src/app.rs`) would show for `id`, and
/// where it came from — the menu tree, this crate's catalog, or (for the
/// few ids the catalog explicitly doesn't duplicate) `palette::COMMANDS`.
/// Mirrors `App::action_title`'s own resolution order exactly, so the
/// generated reference always agrees with what F1 help/the keybinding
/// editor actually shows.
fn resolve_title(id: &str) -> (String, &'static str) {
    fn find(items: &[Item], action: &str) -> Option<String> {
        for it in items {
            if let Some(sub) = it.submenu {
                if let Some(label) = find(sub, action) {
                    return Some(label);
                }
            } else if it.action == action {
                return Some(it.label());
            }
        }
        None
    }
    if let Some(label) = menu::menus().iter().find_map(|m| find(m.items, id)) {
        return (label, "Menu");
    }
    if let Some(key) = action_catalog::title_key(id) {
        return (t!(key).to_string(), "Catalog");
    }
    if let Some(&(label_key, _)) = COMMANDS.iter().find(|(_, action)| *action == id) {
        return (t!(label_key).to_string(), "Palette");
    }
    (id.to_string(), "Untitled")
}

fn render_actions(root: &Path) -> String {
    let dispatchable = dispatch_scan::every_dispatchable_action_id(root);
    let mut out = String::new();
    out.push_str("# Action Reference\n\n");
    out.push_str(
        "Generated by `cargo run --example list_commands -- --write` (T305, \
         `tasks.md`) — do not edit by hand. Every action id \
         [`App::run_action`](https://github.com/vixide/vix) can dispatch, with the \
         title it resolves to and where that title comes from: a **Menu** leaf, this \
         workspace's `vix-action-catalog` (**Catalog**, for ids with no menu leaf of \
         their own), or a `palette::COMMANDS` entry (**Palette**, the few ids titled \
         only there).\n\n",
    );
    let _ = writeln!(
        out,
        "A handful of ids are dynamically suffixed (`view.theme:Dark`, \
         `script:my_script`, …) rather than literal — their bare prefixes ({}) \
         are exempt from this list; see \
         `vix_action_catalog::dispatch_scan::DYNAMIC_PREFIXES`.\n",
        dispatch_scan::DYNAMIC_PREFIXES
            .iter()
            .map(|p| format!("`{p}`"))
            .collect::<Vec<_>>()
            .join(", ")
    );
    out.push_str("| Action ID | Title | Source |\n");
    out.push_str("| --- | --- | --- |\n");
    let mut rows = 0usize;
    for id in &dispatchable {
        if dispatch_scan::DYNAMIC_PREFIXES
            .iter()
            .any(|p| id.starts_with(p))
        {
            continue;
        }
        let (title, source) = resolve_title(id);
        let _ = writeln!(out, "| `{id}` | {} | {source} |", escape_cell(&title));
        rows += 1;
    }
    let _ = write!(out, "\n**{rows} actions.**\n");
    out
}

/// One `Settings` struct field: its name, its literal Rust type (as written
/// in `crates/vix-settings/src/lib.rs`), and its doc comment (joined into
/// one line).
struct SettingsField {
    name: String,
    ty: String,
    doc: String,
}

/// Parse `crates/vix-settings/src/lib.rs`'s own `pub struct Settings { .. }`
/// body: each field's doc comment (consecutive `///` lines immediately
/// above it) and its `name: Type` declaration, in source order.
///
/// # Panics
///
/// Panics if no fields are found — a signal this parser has drifted from a
/// real shape change in `Settings`, not a silently wrong scan.
fn parse_settings_fields(src: &str) -> Vec<SettingsField> {
    let mut fields = Vec::new();
    let mut in_struct = false;
    let mut depth = 0i32;
    let mut doc_buf: Vec<String> = Vec::new();
    for line in src.lines() {
        let trimmed = line.trim();
        if !in_struct {
            if trimmed.starts_with("pub struct Settings {") {
                in_struct = true;
                depth = 1;
            }
            continue;
        }
        if let Some(text) = trimmed.strip_prefix("///") {
            doc_buf.push(text.trim().to_string());
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("pub ")
            && let Some(colon) = rest.find(':')
        {
            let name = rest[..colon].trim().to_string();
            let ty = rest[colon + 1..]
                .trim()
                .trim_end_matches(',')
                .trim()
                .to_string();
            let doc = strip_intradoc_links(&doc_buf.join(" "));
            fields.push(SettingsField { name, ty, doc });
            doc_buf.clear();
            continue;
        }
        depth += i32::try_from(trimmed.matches('{').count()).unwrap_or(0);
        depth -= i32::try_from(trimmed.matches('}').count()).unwrap_or(0);
        if depth == 0 {
            break;
        }
    }
    assert!(
        !fields.is_empty(),
        "found no Settings fields — did the struct move or rename?"
    );
    fields
}

/// A JSON-serialized default value, formatted for a markdown table cell.
fn format_default(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::Null => "`null`".to_string(),
        serde_json::Value::String(s) if s.is_empty() => "`\"\"`".to_string(),
        serde_json::Value::String(s) => format!("`{s:?}`"),
        serde_json::Value::Array(a) if a.is_empty() => "`[]`".to_string(),
        serde_json::Value::Bool(_)
        | serde_json::Value::Number(_)
        | serde_json::Value::Array(_)
        | serde_json::Value::Object(_) => format!("`{v}`"),
    }
}

fn render_settings(root: &Path) -> String {
    let src_path = root.join("crates/vix-settings/src/lib.rs");
    let src = fs::read_to_string(&src_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", src_path.display()));
    let fields = parse_settings_fields(&src);

    let defaults =
        serde_json::to_value(Settings::default()).expect("Settings::default() always serializes");
    let defaults = defaults
        .as_object()
        .expect("Settings serializes to a JSON object");

    let mut out = String::new();
    out.push_str("# Settings Reference\n\n");
    out.push_str(
        "Generated by `cargo run --example list_commands -- --write` (T305, \
         `tasks.md`) — do not edit by hand. Every [`Settings`](../../crates/vix-settings/spec/index.md) \
         field: its persisted key (the flat TOML key in `config.toml`), its Rust type, \
         its default value, and its doc comment.\n\n",
    );
    out.push_str("| Key | Type | Default | Description |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for f in &fields {
        let default = defaults
            .get(&f.name)
            .map_or_else(|| "—".to_string(), format_default);
        let _ = writeln!(
            out,
            "| `{}` | `{}` | {default} | {} |",
            f.name,
            escape_cell(&f.ty),
            escape_cell(&f.doc)
        );
    }
    let _ = write!(out, "\n**{} settings.**\n", fields.len());
    out
}

/// One line for a single key binding: the key token, the action's resolved
/// title, and its id.
fn binding_row(token: &str, action_id: &str) -> String {
    let (title, _) = resolve_title(action_id);
    format!("| `{token}` | {} | `{action_id}` |\n", escape_cell(&title))
}

fn render_shared_keybindings() -> String {
    let mut out = String::new();
    out.push_str("# Shared Keybindings\n\n");
    out.push_str(
        "Generated by `cargo run --example list_commands -- --write` (T305, \
         `tasks.md`) — do not edit by hand. Bindings every keymap shares \
         (`vix_keybindings::SHARED`), on top of whichever keymap-specific page \
         applies.\n\n",
    );
    out.push_str("| Key | Action | Action ID |\n");
    out.push_str("| --- | --- | --- |\n");
    for b in keybindings::SHARED {
        out.push_str(&binding_row(b.key_token, b.action_id));
    }
    let _ = write!(
        out,
        "\n**{} shared bindings.**\n",
        keybindings::SHARED.len()
    );
    out
}

fn render_keymap_keybindings(keymap: &vix::keymap_model::Keymap) -> String {
    let table = keybindings::TABLES
        .iter()
        .find(|t| t.keymap_id == keymap.id)
        .unwrap_or_else(|| panic!("no vix_keybindings::TABLES entry for {}", keymap.id));

    let mut out = String::new();
    let _ = writeln!(out, "# {} Keybindings\n", keymap.name);
    let _ = writeln!(
        out,
        "Generated by `cargo run --example list_commands -- --write` (T305, \
         `tasks.md`) — do not edit by hand. {}. Every binding also gets the \
         [shared bindings](keybindings-shared.md) every keymap has.\n",
        keymap.tooltip
    );

    let mut total = 0usize;
    for ctx in table.contexts {
        let heading = if ctx.name.is_empty() {
            "Top level".to_string()
        } else {
            format!("After `{}`", ctx.name)
        };
        let _ = writeln!(out, "## {heading}\n");
        out.push_str("| Key | Action | Action ID |\n");
        out.push_str("| --- | --- | --- |\n");
        // Bindings carry no inherent order; sort by key token so the page is
        // stable and scannable rather than reflecting declaration order.
        let mut bindings: Vec<_> = ctx.bindings.iter().collect();
        bindings.sort_by_key(|b| b.key_token);
        for b in &bindings {
            out.push_str(&binding_row(b.key_token, b.action_id));
        }
        out.push('\n');
        total += ctx.bindings.len();
    }
    let _ = writeln!(
        out,
        "**{total} bindings** (plus the shared bindings above)."
    );
    out
}

/// Escape a value for a markdown table cell: `|` would otherwise end the
/// cell early, and a raw newline would break the row.
fn escape_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Strip rustdoc intra-doc links (`` [`text`](Self::field) ``) out of field
/// doc text pulled verbatim from the source: they resolve inside rustdoc,
/// but `Self::field` means nothing as a markdown link target in a generated
/// reference page — `scripts/check-docs` (rightly) reports it as broken.
/// Keeps the link's own label text in place of the whole `[label](target)`.
fn strip_intradoc_links(s: &str) -> String {
    let mut out = String::new();
    let mut rest = s;
    while let Some(link_start) = rest.find("](Self::") {
        let (Some(bracket_start), Some(paren_end_rel)) =
            (rest[..link_start].rfind('['), rest[link_start..].find(')'))
        else {
            break;
        };
        out.push_str(&rest[..bracket_start]);
        out.push_str(rest[bracket_start + 1..link_start].trim_matches('`'));
        rest = &rest[link_start + paren_end_rel + 1..];
    }
    out.push_str(rest);
    out
}
